### PR TITLE
Overhaul portal UI, replace homepage and main navigation.

### PR DESCRIPTION
**Pull request by charliemeyer**

### CODE REVIEW

**Comment by tcmitchell** [comment]
No description of this massive and fabulous change? Really?

Some things to fix:
* cards.js is really an HTML file, not a JavaScript file. Can the script tags be moved to where it is included so that it's really a JavaScript file as it should be?
* I see no uses of the following images, which I think were replaced by Google's Material design icons
  - email.png
 - external.png
 - geni-square.png
 - green.png
 - yellow.png
 - red.png
 - *Don't forget to remove them from the Makefile if you delete them*
* Copyrights on new files should only list the year 2015, not any previous years:
 - dashboard.js
 - dashboard.php
 - genimap.php
 - preferences.php

**Comment by charliemeyer** [comment]
On the topic of removing old things, should I remove the old portal.css file and the "show old header" function?

**Comment by tcmitchell** [comment]
> On the topic of removing old things, should I remove the old portal.css file and the "show old header" function?

No, not yet.

**Comment by charliemeyer** [comment]
Sure thing. The items above are done now.

**Pull request merged**
