### PR TITLE
Tkt1318 logs

### PR DESCRIPTION
**Pull request by charliemeyer**
Add dropdown to get logs for a given time period on homepage (#1318)

Moved code to get log messages into file do-get-logs.php. Added a select on the homepage that makes an ajax request to do-get-logs with the requested number of hours of log messages when it changes, and redisplays the updated table.

### CODE REVIEW

**Comment by ahelsing** [comment]
Please restore the defaults for $num_hours in logging_client.php, and then have a default for $num_hours in your new class, and pull 'hours' out of $_REQUEST instead of $_GET.

Additionally, list the changes for #1375 in the CHANGES file.

Make those changes and push to your branch. That should update this pull request automatically.

**Comment by charliemeyer** [comment]
wait a sec on that last commit, I missed something

**Comment by ahelsing** [comment]
I think you mistakenly added portal/www/images/geni-header-left.png and portal/www/images/geni-header-right.png

In addition, do-get-logs.php needs to use `$_REQUEST` in one more spot where you currently use `$_GET`.

**Comment by charliemeyer** [comment]
bizzarre that those images got added, I'll push them later with the real changes. I fixed the do-get-logs thing as well, missed that earlier sorry.

**Pull request merged**
