### PR TITLE
Make maps on the portal Google maps

### PR DESCRIPTION
**Pull request by charliemeyer**
Loads faster, scrolls more smoothly, pins behave better when clicked. Thanks, Google!

### CODE REVIEW

**Comment by tcmitchell** [comment]
The markers obscure each other, unfortunately. Charlie is investigating clustering libraries to improve the situation.

**Comment by charliemeyer** [comment]
Recent commits make it so all maps on the portal are Google maps.

**Comment by charliemeyer** [comment]
These changes are ready to be evaluated for merging into develop

**Comment by tcmitchell** [comment]
Fixes #1272.

**Pull request merged**
