### PR TITLE
Add Google analytics (via adding header) to jacks-expanded views.

### LINKED ISSUE #1488: Add google analytics to "expanded view" pages.
These include jacks-app-expanded.php and jacks-editor-app-expanded.php. Should be as simple as including header.php in both files.

### PR DESCRIPTION
**Pull request by charliemeyer**
Fixes #1488.

### CODE REVIEW

**Comment by tcmitchell** [comment]
I can see that google analytics has been enabled on the two jacks expanded pages by watching the analytics real-time content. There are issues with each page, however. See next comments.

**Comment by tcmitchell** [comment]
The jacks-app-expanded page displays jacks with a very short height in Chrome, Firefox, and Safari:

screen shot 2015-08-07 at 12 10 43 pm

**Comment by tcmitchell** [comment]
The jacks-editor-app-expanded has no palette of nodes & sites to drag onto the jacks canvas. I can't tell if it is a CSS issue or an initialization issue or what. It happens on Chrome, Firefox, and Safari:

screen shot 2015-08-07 at 12 12 25 pm

**Comment by charliemeyer** [comment]
Combined with the changes of #1502, the jacks-expanded pages should look good and be totally usable.

**Pull request merged**
